### DISCUSSION TITLE
What would be the best OLED settings with this extension

### DISCUSSION THREAD

**Discussion by TheForgotten69** [ThomazPom/Moz-Ext-UltimaDark#119] [Q&A] [answered]
Hi all, 
I just discovered this wonderful extension after many many days to pinpoint my issue what with dark reader...
In dark reader, for best "oled" mode, I set the contrast as +50 which effectively set the background as pitch black (#000000)
How to replicate the same? I'm a bit lost in the setting page tbh

**Comment by zkvsky** [comment]
I was planning to ask a similar question? How the heck do you increase contrast to make the background colours pure black?

**Comment by ThomazPom** [comment]
Hi, thanks for your excellent question! The advanced settings page is not implemented yet and is currently non-functional. My main idea for this planned feature is not to increase contrast but to floor the lightness, optimizing the display for OLED screens.

If you’d like to achieve this behavior right now, you can use Stylus alongside UltimaDark for a quick but not perfect solution. Here’s a guide to get you started:
https://chatgpt.com/share/6757c7ad-0bcc-8001-818a-f41e76ffee52

Let me know if you’d like further tweaks!

**Reply by TheForgotten69** [reply]
Thanks @ThomazPom for the answer. Is this feature planned for the next version or just a future plan?  :)
I'll test the stylus + UltimaDark solution and report back. Honestly as long as it's more stable/quicker than dark reader would already be a win

**Reply by TheForgotten69** [reply]
Coming back here, I can attest that UltimaDark + Stylus is indeed quicker (50% on my case on the speedometer 3.0) albeit differences
![dark reader](https://github.com/user-attachments/assets/b49fb1fc-2835-4af0-85aa-7c721d96ffa8)
vs
![ultima_stylus](https://github.com/user-attachments/assets/47afad83-1434-40b1-8b5e-78541d1a6374)

The above also has the tendency to make the images darker but even with these caveat I'll continue forward with this solution going on

**Reply by TheForgotten69** [reply]
I'm using this in stylus, much better but many many tweaks will be required I guess (I hate css haha)
```css
::-moz-selection {
    background-color: #264f78 !important;
    color: #ffffff !important;
}

/* Special handling for code blocks selection */
pre::selection, code::selection,
pre *::selection, code *::selection {
    background-color: #adb9c4 !important;
    color: #ffffff !important;
}

pre::-moz-selection, code::-moz-selection,
pre *::-moz-selection, code *::-moz-selection {
    background-color: #264f78 !important;
    color: #ffffff !important;
}

/* Force pure black background everywhere */
html, body, div, section, article, aside, nav, header, footer, main, 
.container, .content, .wrapper, .page, .main, .background,
[class*="bg-"], [class*="background"], [style*="background"] {
    background-color: #000 !important;
    background-image: none !important;
}

/* Handle any elements with background color */
* {
    background-color: #000 !important;
}

/* Adjust text contrast without affecting images */
p, h1, h2, h3, h4, h5, h6, span, div:not(:has(img)) {
    color: #e0e0e0 !important;
}

/* Preserve image quality while ensuring good visibility */
img {
    opacity: 0.9;
    filter: brightness(0.9) !important;
}

/* Enhance readability for links */
a:not(:hover) {
    color: #8ab4f8 !important;
}

a:hover {
    color: #adc8ff !important;
}

/* Adjust background colors for content areas */
article, main, section {
    background-color: #000 !important;
    color: #e0e0e0 !important;
}

/* Improve contrast for code blocks and pre elements */
pre, code {
    background-color: #1a1a1a !important;
    color: #e0e0e0 !important;
}
```
